ALTER TABLE survivor_candidates ADD COLUMN first_seen_price_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN first_seen_price_source TEXT;
ALTER TABLE survivor_candidates ADD COLUMN current_price_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN ath_price_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN ath_at TEXT;
ALTER TABLE survivor_candidates ADD COLUMN drawdown_pct TEXT;
ALTER TABLE survivor_candidates ADD COLUMN age_seconds INTEGER;
ALTER TABLE survivor_candidates ADD COLUMN price_status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE survivor_candidates ADD COLUMN price_source TEXT;
ALTER TABLE survivor_candidates ADD COLUMN price_updated_at TEXT;
ALTER TABLE survivor_candidates ADD COLUMN price_age_ms INTEGER;
ALTER TABLE survivor_candidates ADD COLUMN candidate_eligible INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN active_candidate INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN audit_state TEXT NOT NULL DEFAULT 'NOT_REQUESTED';
ALTER TABLE survivor_candidates ADD COLUMN audit_requested INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN audit_failed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN quote_state TEXT NOT NULL DEFAULT 'NOT_REQUESTED';
ALTER TABLE survivor_candidates ADD COLUMN quote_requested INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN ready_to_buy INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN paper_buy INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN native_token_price_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN liquidity_current_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN liquidity_1m_ago_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN liquidity_2m_ago_usd TEXT;
ALTER TABLE survivor_candidates ADD COLUMN buy_volume_30s TEXT NOT NULL DEFAULT '0';
ALTER TABLE survivor_candidates ADD COLUMN sell_volume_30s TEXT NOT NULL DEFAULT '0';
ALTER TABLE survivor_candidates ADD COLUMN buy_volume_1m TEXT NOT NULL DEFAULT '0';
ALTER TABLE survivor_candidates ADD COLUMN sell_volume_1m TEXT NOT NULL DEFAULT '0';
ALTER TABLE survivor_candidates ADD COLUMN buy_volume_3m TEXT NOT NULL DEFAULT '0';
ALTER TABLE survivor_candidates ADD COLUMN sell_volume_3m TEXT NOT NULL DEFAULT '0';
ALTER TABLE survivor_candidates ADD COLUMN buy_count_1m INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN sell_count_1m INTEGER NOT NULL DEFAULT 0;
ALTER TABLE survivor_candidates ADD COLUMN buy_sell_volume_ratio_1m TEXT;
ALTER TABLE survivor_candidates ADD COLUMN buy_sell_count_ratio_1m TEXT;
ALTER TABLE survivor_candidates ADD COLUMN price_change_1m TEXT;
ALTER TABLE survivor_candidates ADD COLUMN source_status_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE survivor_candidates ADD COLUMN last_price_attempt_at TEXT;

ALTER TABLE survivor_flow_samples ADD COLUMN price_source TEXT;
ALTER TABLE survivor_flow_samples ADD COLUMN liquidity_usd TEXT;
